title: 냥파 랜드
author: MeowPiE
email: email@meowpie.kr
description: 빛나는 냥파이의 정보 나라
url: https://blog.meowpie.kr
timezone: Asia/Seoul
image: # put blog logo image

permalink: /:title/
paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
